### ISSUE TITLE
Method POPUP not working

### ISSUE THREAD

**Issue by dycsi-gabrielbaca** [epeterson320/ABAP-Logger#16]
Method POPUP is not working due to the attribute ME->HANDLE sent to function module BAL_DSP_LOG_DISPLAY. A handle table is expected, instead of a single handle. The correction applied was this:

```
  method popup.
    data: profile type bal_s_prof,
          t_handle type BAL_T_LOGH. " Correction

    call function 'BAL_DSP_PROFILE_POPUP_GET'
      importing
        e_s_display_profile = profile.

    append me->handle to t_handle. " Correction
    call function 'BAL_DSP_LOG_DISPLAY'
      exporting
        i_s_display_profile = profile
        i_t_log_handle      = t_handle. " Correction

  endmethod.
```

**Comment by apex8** [comment]
@dycsi-gabrielbaca I have already a PR for this issue which is also affecting the fullscreen() method.
@epeterson320 See PR

**Comment by epeterson320** [comment]
I've accepted the PR. Let me know if it's working now.

**Comment by DennstedtB** [comment]
I know this issue is quite old. And you may already know it, but it works. So you could close the issue.
