### ISSUE TITLE
Expiry Date

### ISSUE THREAD

**Issue by andkopp** [epeterson320/ABAP-Logger#17]
It would be nice if we could provide the expiry date for log entries. The expiry date is an important attribute for transaction SLG2 which deletes expired logs.

Suggestion: I can add expiry_date as parameter (data element: ALDATE_DEL) for the methods new() and open() and set it on SLG header. What do you think about this?

**Comment by apex8** [comment]
Hi Adreas,

I guess such a feature would be nice. In support scenarios sometimes it
would be nice to have a look the application log to find out some more
information about a reported problem. Its always too bad if those
information are already deleted.

Regards
Alexander

**Comment by andikade** [comment]
Expiry date would be an optional parameter so you won't have to set it. If you set it, you have full control about the earliest date of deletion and you can easily realize sliding windows.

**Comment by andkopp** [comment]
I am working on this feature here: https://github.com/andkopp/ABAP-Logger/commit/167762f75913c5d45b7382af75a1eccbbacd3afe

**Comment by epeterson320** [comment]
Really good stuff. Love the API of the settings object.

**Comment by andkopp** [comment]
I am glad that you like it. I am still testing the changes in our quality assurance system.

**Comment by andkopp** [comment]
Pull request https://github.com/epeterson320/ABAP-Logger/pull/37 created and merged to master.
