### ISSUE TITLE
Change initial to supplied

### ISSUE THREAD

**Issue by BlueTeck** [epeterson320/ABAP-Logger#23]
Hi,

I would suggest to change to following line:
```
if obj_to_log is initial.
```
https://github.com/epeterson320/ABAP-Logger/blob/master/zcl_logger.clas.abap#L210

to

```
if obj_to_log is not supplied.
```

Otherwise a message is created if an empty return table is passed to the method.

Regards,
Timo

**Comment by andkopp** [comment]
Hi,
you can do a pull request. Please check if all unit tests still pass.

BR Andreas

**Comment by andkopp** [comment]
Thank you for your contribution.
