### ISSUE TITLE
Type conflict when calling a function module.

### ISSUE THREAD

**Issue by tamertasdelen** [epeterson320/ABAP-Logger#3]
Hi Eric,

Thanks for you development,

today,  when i tried to do, some errors have caused. 

its the code what i had written

REPORT ZTA_TEMP2.
DATA: log TYPE REF TO zcl_logger.
BREAK-POINT.

CREATE OBJECT log.

log = zcl_logger=>new( object = 'ZTAMER'
                       subobject = 'ACCOUNTING'
                       desc = 'Stuff imported from legacy systems' ).
log->e( 'You see, what had happened was...' ).

BREAK-POINT.
LOG->POPUP( ).

and error is - 

Error in the ABAP Application Program

The current ABAP program "ZCL_LOGGER====================CP" had to be
 terminated because it has
come across a statement that unfortunately cannot be executed.

A function module was called incorrectly.

  1 method POPUP.
  2 \* See SBAL_DEMO_04_POPUP for ideas
  3
  4   DATA: profile TYPE bal_s_prof.
  5   CALL FUNCTION 'BAL_DSP_PROFILE_POPUP_GET'
  6     IMPORTING
  7       e_s_display_profile = profile.
  8

> > >   CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'
> > >  10     EXPORTING
> > >  11       i_s_display_profile    = profile
> > >  12       i_t_log_handle         = me->handle.
> > >  13
> > >  14 endmethod.

thank you for reply

**Comment by tporcham** [comment]
The popup method has an error.
You can change its code to

method POPUP.
* See SBAL_DEMO_04_POPUP for ideas

  DATA: profile TYPE bal_s_prof.
  CALL FUNCTION 'BAL_DSP_PROFILE_POPUP_GET'
    IMPORTING
      e_s_display_profile = profile.

  data lt_handles type BAL_T_LOGH.
  append me->handle to lt_handles.

  CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'
    EXPORTING
      i_s_display_profile    = profile
      i_t_log_handle         = lt_handles.
endmethod.

With this change the method works for me.

**Comment by tamertasdelen** [comment]
Thank you for your comment,

İ had solved it before :)
