### ISSUE TITLE
Adding status checks: has_errors, has_warnings, is_empty

### ISSUE THREAD

**Issue by sbcgua** [epeterson320/ABAP-Logger#38]
Suggest adding the above helpers to the interface. There is a clear workaround with `export_to_table` but is need several code lines which is inconvenient fr a status check.
If agreed I can PR :)

**Comment by sbcgua** [comment]
... and maybe `count` as well (or instead of is_empty) ...

**Comment by andkopp** [comment]
I like your approach of adding query methods. I think they can be quite useful.

The only thing I am wondering is if the interface ZIF_LOGGER will get overloaded over time if we add these query methods directly to the logger interface. What do you think? 3 or 4 methods should still be ok.

**Comment by sbcgua** [comment]
> ...  will get overloaded over time ...

May happen ... :) But imho if the methods are semantically meaningful it should be OK. I would certainly add `has_*` and both `is_empty` and `count` (or `length` ?) can be also useful. So if you don't mind I'd add all of them.
