### ISSUE TITLE
Logging doesn't work when rollback is executed. 

### ISSUE THREAD

**Issue by tporcham** [epeterson320/ABAP-Logger#4]
Hi,

here's my litte sample sample report that shows the issue:
###### 

REPORT ZLOGTEST.
DATA: log TYPE REF TO zcl_logger.
log = zcl_logger=>new( object = 'TEST'
                       subobject = 'TESTSUB1'
                       desc = 'Test' ).

DATA(l_flight) = VALUE sflight( carrid = 'ZP' connid = '77' fldate = sy-datum ).
MODIFY sflight FROM l_flight.
...
*Something bad happened
log->e( 'Oh oh, there was a problem. Could not save sflight.' ).

rollback work.
write: / 'End.'.
###### 

The problem is that the logged message is not saved.
I cannot find the message in transaction SLG1.
Because of the rollback work statement all database changes including the log are discarded.

However, I found a simple solution to this problem.

In method ADD of class ZCL_LOGGER the function module BAL_DB_SAVE is called.
If you set the parameters I_2TH_CONNECTION and I_2TH_CONNECT_COMMIT to true it works as expected. E.G:

CALL FUNCTION 'BAL_DB_SAVE'
      EXPORTING
        i_t_log_handle   = log_handles
        I_2TH_CONNECTION           = abap_true
        I_2TH_CONNECT_COMMIT       = abap_true
      IMPORTING
        e_new_lognumbers = log_numbers.

The trick is to tell the function module to use a secondary database connection to save the log.
C.f. http://help.sap.com/abapdocu_740/en/abenopensql_multiconnect.htm
This way the main logical unit of work is rolled back, but the log is still saved.

Should the logger always use the 2nd connection? Or should the logger have an option to turn on the usage of the sec. connection?
What do you think?

Cheers,

Thomas

**Comment by epeterson320** [comment]
I don't see any downside to always using the 2nd connection.

**Comment by smb** [comment]
IMO default to 2nd but allow to disable it just like autosave would be nice

**Comment by andikade** [comment]
I tried it and it seems to work for me.
A param to control it would be nice. Using the 2nd connection should be the default.
