### ISSUE TITLE
change externalId / desc

### ISSUE THREAD

**Issue by schealex** [epeterson320/ABAP-Logger#54]
Hi,

first of all this is an amazing logger thanks for all the work. My current project has a requirement to change the externalId of the log (desc) you supply to **create_log**. Is there any way to achieve this? I'm not even sure if you can do that at all...

any help on this is greatly apprechiated!

Regards
Alex

**Comment by vidyadharg** [comment]
Please check Function module BAL_LOG_HDR_CHANGE, Please do where-used list for the same.

**Comment by schealex** [comment]
thanks man, thats exactly what i was looking for! i will implement it on a extension of the logger!
if anyone else needs that kind of functionality i could also do a PR afterwards!
