### ISSUE TITLE
Support for chained exceptions

### ISSUE THREAD

**Issue by nununo** [epeterson320/ABAP-Logger#61]
I often use chained exceptions, making use of the `previous` standard attribute. This is a best practice explained here:
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-sub-classes-to-enable-callers-to-distinguish-error-situations

Example:
```ABAP
TRY.
    b = a / 0.
  CATCH cx_divide_by_zero INTO DATA(exc).
    RAISE EXCEPTION TYPE zcx_myapp
      EXPORTING
        previous = exc.
ENDTRY.
 ```

This means that the actual relevant description of the exception is at he bottom level of the chain, accessible via the `previous` attribute.

It would be great to have an option when adding an OO exception. That option would decide what to register:
- only the top exception
- only the bottom exception
- all exceptions in the chain

Something recursive should do the trick. I can attempt to do a PR if you believe this makes sense.

Thanks,
Nuno

**Comment by AlexandreHT** [comment]
Currently it logs all exceptions in the chain (up to 10 levels by default, cf. max_exception_drill_down).

I have a take-it-all approach to logging therefore I don't really see the use cases of the 2 other options.

I you developp it, I'd be in favor of creating new methods rather that adding new parameters (the fewer the better says CleanCode : http://wiki.c2.com/?TooManyParameters)

**Comment by nununo** [comment]
Damn, somehow I didn't realise it was already registering the whole chain.
Sorry for wasting your time with this useless issue.

Actually I also favour the take-it-all approach. The other two were just because "why not! But it's already perfectly fine as it is.

Thanks for a great tool.

Closing it.
