### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by apex8** [epeterson320/ABAP-Logger#7]
Hi,
first I want to say, that I really like the flexibility which this project/class brings. 
However I would like to know, how you would like others to use this? My question is based on the Licence you choose for this project. The GPL dictates that every project which uses GPL licenced code will also become GPL licensed. In the projects where I work this is not intended, so practically I cannot use your class there.
Did you intend knowledge sharing with this project? In that case the GPL is totally fine. But if you had in mind that others can use this component in their customer projects (what I would love to do) the GPL mostly is a blocker for customers, because it´s kind of ("infecting" as I was told. In that case you might consider to switch to the BSD licence.

Best Regards
Alex

**Comment by smb** [comment]
+1

**Comment by epeterson320** [comment]
Hi Alex, thanks for bringing that up. I wasn't familiar with open-source licenses when I started this project, so I've switched to the MIT license, which should allow everything the BSD allows.
